# Identificação do projeto
sonar.projectKey=meli-challenge-orders
sonar.projectName=meli-challenge-orders
sonar.projectVersion=1.0

# Diretório do código-fonte
sonar.sources=.

# Linguagem do projeto
sonar.language=go

# Diretórios a serem excluídos da análise
sonar.exclusions=**/api-handlers/**,**/cli/**,**/mocks/**,**/docs/**,**/test/**,**/ports/**,**/inputs/**,**/main.go,**/*_test.go


# Relatório de cobertura de testes
sonar.go.coverage.reportPaths=coverage.out

# URL do servidor SonarQube
sonar.host.url=http://127.0.0.1:9000

# Token gerado no SonarQube
sonar.login=squ_9b0f2da84dccfd6459e60fe2bdd44cdb5ba8c462