services:

  distribution_centers:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_HOST: distribution_centers_mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: distribution_centers_db
      API_PORT: 8081
    networks:
      - distribution_centers_network
    depends_on:
      - distribution_centers_mysql

  distribution_centers_mysql:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      MYSQL_DATABASE: distribution_centers_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - distribution_centers_network
    volumes:
      - ./.docker/mysql-init:/docker-entrypoint-initdb.d
      - distribution_centers_db_data:/var/lib/mysql

  distribution_centers_mysql-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9091:80"
    environment:
      PMA_HOST: distribution_centers_mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - distribution_centers_network
    depends_on:
      - distribution_centers_mysql

networks:
  distribution_centers_network:

volumes:
  distribution_centers_db_data: