// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/orders": {
            "post": {
                "description": "Create an order with specific products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Create an order",
                "parameters": [
                    {
                        "description": "Order Input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateOrderInputDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreatedOrderOutputDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/{orderId}": {
            "get": {
                "description": "Get all events with their details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "List all events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreatedOrderOutputDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": " message about the error"
                }
            }
        },
        "dtos.CreateOrderInputDTO": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ProductInputDTO"
                    }
                },
                "state": {
                    "type": "string",
                    "example": "SP"
                },
                "zone": {
                    "description": "choosing criteria",
                    "type": "string",
                    "example": "S1"
                }
            }
        },
        "dtos.CreatedOrderOutputDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-04-07T22:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "adec01f0-0393-436d-a441-04575e6624bb"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ProductOutputDTO"
                    }
                },
                "products_count": {
                    "type": "integer",
                    "example": 3
                },
                "state": {
                    "type": "string",
                    "example": "SP"
                },
                "status": {
                    "type": "string",
                    "example": "PENDING"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-04-07T22:30:00Z"
                },
                "zone": {
                    "type": "string",
                    "example": "S1"
                }
            }
        },
        "dtos.DistributionCenterOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "a2d705c1-7431-456b-b65f-bee431694b46"
                },
                "name": {
                    "type": "string",
                    "example": "DC1"
                },
                "zone": {
                    "type": "string",
                    "example": "S1"
                }
            }
        },
        "dtos.ProductInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "2b494226-db60-4dd0-b2a0-141b3ae52517"
                },
                "name": {
                    "type": "string",
                    "example": "Product A"
                },
                "price": {
                    "type": "number",
                    "example": 10.5
                },
                "quantity": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "dtos.ProductOutputDTO": {
            "type": "object",
            "properties": {
                "distribution_center": {
                    "$ref": "#/definitions/dtos.DistributionCenterOutputDTO"
                },
                "id": {
                    "type": "string",
                    "example": "3195b102-353a-4d84-9639-7eda62ef5f08"
                },
                "name": {
                    "type": "string",
                    "example": "Product A"
                },
                "price": {
                    "type": "number",
                    "example": 10.5
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Orders API",
	Description:      "This is a server for managing orders.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
